config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # get 'pages/home', to: 'pages#home'
  # get 'pages/about', to: 'pages#about'
 root 'articles#home'
 resources :articles
 resources :users, except: [:new]
 get 'signup', to: "users#new"
 

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord

	belongs_to :user

	validates :title, presence: true, length: {minimum: 3, maximum: 50}
	validates :description, presence: true, length: {minimum: 10, maximum: 3000}
	validates :user_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord

	has_many :articles

	before_save { self.email = email.downcase }
	validates :username, presence: true, length: {minimum: 3, maximum: 25}
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
	validates :email, presence: true, uniqueness: {case_sensitive: false}, format: { with: VALID_EMAIL_REGEX }

	has_secure_password

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	before_action :set_article, only: [:edit, :update, :show, :destroy]

	def index 
		@articles = Article.all
	end

	def new
		@article = Article.new
	end

	def create
		@article = Article.new(article_params)
		@article.user = User.first
		if @article.save
			flash[:success] = "Article was successfully created"
			redirect_to article_path(@article)
		else
			render 'new'
		end
	end

	def home

	end

	def show

	end

	def edit
	
	end

	def update
		if @article.update(article_params)
			flash[:success] = "Article was successfully updated"
			redirect_to article_path(@article)
		else 
			render 'edit'
		end
	end

	def destroy
		if @article.present?
			@article.destroy
			flash[:danger] = "Article was successfully deleted"
			redirect_to articles_path
		end
	end

	private

		def set_article
			@article = Article.find(params[:id])
		end

		def article_params
			params.require(:article).permit(:title, :description)
		end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def index
		@users = User.all
	end

	def new 
	  @user = User.new
	end

	def create 
		@user = User.new(user_params)
		if @user.save
			flash[:success] = "Congrats #{@user.username}. You have signed in successfully!"
			redirect_to articles_path
		else 
			render 'new'
		end
	end

	def edit
		@user = User.find(params[:id])
	end

	def update
		@user = User.find(params[:id])
		if @user.update(user_params)
			flash[:success] = "Hey #{@user.username}. You successfully updated your account"
			redirect_to articles_path
		else 
			render 'edit'
		end
	end

	def show
		@user = User.find(params[:id])
	end

	private

	def user_params
		params.require(:user).permit(:username, :email, :password)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper

	def gravatar_for(user,option={size: 80})
		gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
		size = option[:size]
		gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
		image_tag(gravatar_url, alt: user.username, class: "img-circular")
	end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/edit.html.erb
<h1 align="center">Edit your article</h1>

<%= render :partial => 'partials/form.html.erb' %>

app/views/articles/home.html.erb
<div class="center_align jumbotron">
	<h1>Hello! Welcome to Alpha blog!!</h1>
	<%= link_to "Sign Up Now", "#", class: "btn btn-primary btn-lg center btn-xlarge" %>	
</div>

app/views/articles/index.html.erb
<%= render 'partials/articles', object: @articles %>

app/views/articles/new.html.erb
<h1>Create new article</h1>

<% if @article.errors.any? %>
<h2>The following errors are getting created</h2>
<ul>
	<% @article.errors.full_messages.each do |error_msg| %>
			<li>
			<%= error_msg %>			
			</li>
	<% end %>
</ul>
<% end %>



<%= form_for @article do |article| %>
	<p>
		<%= article.label :title %><br>
		<%= article.text_field :title%>
	</p>

	<p>
		<%= article.label :description %><br>
		<%= article.text_area :description %>
	</p>
	<p>
		<%= article.submit %>
	</p>
<% end %>

app/views/articles/show.html.erb
<h2 align="center"> <%= @article.title %></h2>
<div class="well col-xs-8 col-xs-offset-2">
	<ul class="listing">
		<div class="row center_align">
			<div class="col-md-4 col-md-offset-4">
				Created by:
				<li style="margin-top: 5px;">
					<%= link_to gravatar_for(@article.user),	user_path(@article.user) %>
				</li>
				<li class="article_title">
					<%= link_to @article.user.username, user_path(@article.user) %>
				</li>	
				<li>
					<small><%= pluralize(@article.user.articles.count, "article") if @article.user.articles%></small>
				</li>
			</div>
		</div>
	</ul>
	<h4 class="center_align description_alignment"><strong>Description:</strong></h4>
	<hr>	
		<%= simple_format(@article.description) %> 
	</hr>
	<div class="article_actions">
		<%= link_to "Edit", edit_article_path(@article.id), class: "btn btn-xs btn-primary" %>
		<%= link_to "Delete this article", article_path(@article), method: :delete,
			 													   data: {confirm: "Are you sure, you want to delete this article?"}, 
																   class: "btn btn-xs btn-danger"%>
		<%= link_to "Back to listing",  articles_path, class: "btn btn-xs btn-success" %>
	</div>
</div>

app/views/layouts/_messages.html.erb
<div class="row">
	<div class="col-xs-10 col-xs-offset-1">
	    <% flash.each do |name,msg| %>
		    <div class='alert alert-<%="#{name}"%>'>
		    	<a href="#",  class="close" data-dismiss="alert">&#215;</a>
		    	<%= content_tag :div, msg, :id => "flash#{name}" if msg.is_a?(String) %>
		    </div>
    	<% end %>
    </div>
</div> 	 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render :partial => 'partials/navigation.html.erb' %>
    <%= render :partial => 'layouts/messages.html.erb' %>
    <div class="container">
      <%= yield %>  
    </div>
    <%= render :partial => 'partials/footer.html.erb'%>
  </body>
</html>

app/views/partials/_articles.html.erb
<h1 align="center">Here is the list of all your articles</h1>

	<% object.each do |article| %>
	 	<div class="row">
	 		<div class="col-xs-8 col-xs-offset-2">
	 			<div class="well well-lg">
	 				<div class="article_title">
						<%= link_to article.title, article_path(article) %>
					</div>
					<div class="article_body">
						<%= truncate(article.description, length: 100) %>
						<div class="article_meta_details">
							<small>Created by: <%= article.user.username if article.user.present? %>,
								  <%= time_ago_in_words(article.created_at)%> ago,
								  last updated: <%= time_ago_in_words(article.updated_at) %> ago
							</small>
						</div>
					</div>
			
					<div class="article_actions">
						<%= link_to "Edit", edit_article_path(article.id), class: "btn btn-xs btn-primary" %>
						<%= link_to "Delete this article", article_path(article), method: :delete,
							 													   data: {confirm: "Are you sure, you want to delete this article?"}, 
																				   class: "btn btn-xs btn-danger"%>
					</div>
				</div>
			</div>
		</div>
	<% end %>

app/views/partials/_footer.html.erb
<div class="container">
	<footer class="footer">
		<big>
			This is a demo app designed by Jithesh.k
		</big>
		<nav>
			<ul>
				<li>
					<%= link_to "About", "#" %> 
				</li>
			</ul>
		</nav>
	</footer>
</div>

app/views/partials/_form.html.erb
<%= render 'shared/errors.html.erb', obj: @article %>
<div class="row">
	<div class="col-xs-12">
		<%= form_for(@article, :html => {class: "form-horizontal", role: "form"}) do |article| %>
			<div class="form-group">
				<div class="col-sm-2 control-label" >
					<%= article.label :title %>
				</div>
				<div class="col-sm-8">
					<%= article.text_field :title, class: "form-control", placeholder: "Article title", autofocus: true%>
				</div>		
			</div>
			
			<div class="form-group">
				<div class="col-sm-2 control-label" >
					<%= article.label :description %>
				</div>
				<div class="col-sm-8">				
					<%= article.text_area :description,rows: 10, class: "form-control", placeholder: "Article description goes here", autofocus: true %>
				</div>
			</div>
		  	<div class="form-group">
    			<div class="col-sm-offset-2 col-sm-10">
					<%= article.submit class: "btn btn-primary btn-lg" %>
				</div>
			</div>
		<% end %>

		<div class="col-xs-4 col-xs-offset-4">
			<%= link_to "Back to articles listing page",  articles_path %>	
		</div>
    </div>
</div>

app/views/partials/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Alpha Blog", root_path, class: "navbar-brand", id: "logo" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li>
            <%= link_to "Articles", articles_path %>
        </li>
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li>
              <%= link_to "New Article", new_article_path %>
            </li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/partials/_user_signup_or_update.html.erb
<%= render 'shared/errors.html.erb', obj: @user %>
<div class="row">
	<div class="col-xs-12">
		<%= form_for(@user, :html => {class: "form-horizontal", role: "form"}) do |user| %>
			<div class="form-group">
				<div class="col-sm-2 control-label" >
					<%= user.label :username %>
				</div>
				<div class="col-sm-8">
					<%= user.text_field :username, class: "form-control", placeholder: "User name", autofocus: true%>
				</div>		
			</div>
			
			<div class="form-group">
				<div class="col-sm-2 control-label" >
					<%= user.label :email %>
				</div>
				<div class="col-sm-8">				
					<%= user.email_field :email, class: "form-control", placeholder: "Please enter your email", autofocus: true %>
				</div>
			</div>

			<div class="form-group">
				<div class="col-sm-2 control-label" >
					<%= user.label :password %>
				</div>
				<div class="col-sm-8">
					<%= user.password_field :password, class: "form-control", placeholder: "******", autofocus: true%>
				</div>		
			</div>

		  	<div class="form-group">
    			<div class="col-sm-offset-2 col-sm-10">
					<%= user.submit(@user.new_record? ? "Sign up" : "Update my details" ,class: "btn btn-primary btn-lg") %>
				</div>
			</div>
		<% end %>
    </div>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
	<div class="row">
		<div class="col-xs-8 col-xs-offset-2">
			<div class="panel panel-danger">
				<div class="panel panel-heading">
					<h2 class="panel-title">
						<%= pluralize(obj.errors.count, "error") %>
					prohibited the article from being saved: </h2>

					<div class="panel-body">
						<ul>
							<% obj.errors.full_messages.each do |error_msg| %>
									<li>
									<%= error_msg %>			
									</li>
							<% end %>						
						</ul>
					</div>
				</div>
			</div>
		</div>
	</div>
<% end %>

app/views/users/edit.html.erb
<h1 align="center"> Edit your account</h1>

<%= render 'partials/user_signup_or_update' %>

app/views/users/index.html.erb
<h1 align="center"> All alpha bloggers</h1>
<%= @users.each do |user| %>
<div align="center">
	<ul class="listing">
		<div class="row">
			<div class="well col-md-4 col-md-offset-4">
				<li>
					<%= link_to gravatar_for(user),	user_path(user) %>
				</li>
				<li class="article_title">
					<%= link_to user.username, user_path(user) %>
				</li>	
				<li>
					<small><%= pluralize(user.articles.count, "article") if user.articles%></small>
				</li>
			</div>
		</div>
	</ul>
<% end %>
</div>

app/views/users/new.html.erb
<h1 align="center"> Sign up for Alpha Blog</h1>

<%= render 'partials/user_signup_or_update' %>

app/views/users/show.html.erb
<h1 align="center">Welcome to <%= @user.username%>'s page!!</h1>

<div class="row">
	<div class="col-md-4 col-md-offset-4 center_align">
		<%= gravatar_for @user, size: 150 %>
	</div>
</div>

<h4 align="center"><%= @user.username %>'s articles.</h4>

<%= render 'partials/articles', object: @user.articles %>